export const productos = [
  {
    id: 1,
    image:
      "https://www.venex.com.ar/products_images/1638202580_1631815751_notebook-asus-tuf-fx506hc-hn064-i5-11400h-16gb-ssd-512gb-rtx-3050-4gb-15.6.jpg",
    title: "ASUS TUF FX506HCB RTX3050",
    descripcion:
      "Diseñado para juegos serios y con un estilo nuevo y elegante, TUF Gaming F15 es un portátil para juegos Windows 10 Pro repleto de funciones con el poder de llevarte a la victoria. La nueva GPU GeForce RTX ™ 3050 ofrece un juego fluido en una pantalla de hasta 240Hz con 100% sRGB, mientras que la potente CPU Intel® Core ™ se ve reforzada por una refrigeración mejorada que amplifica el rendimiento de la CPU y mantiene la acústica sigilosa. Una batería de larga duración de 90 Wh junto con la durabilidad de grado militar de TUF lo mantiene en su mejor juego en cualquier lugar.",
    category: "ASUS",
    almacenamiento: "512 GB",
    gpu: "Nvidia Rtx 3050 4GB GDDR6",
    ram: "16 GB",
    cpu: "Intel Core i5 11400H 4.50Ghz 12mb",
    sistema: "Windows 10 Home 64 Bits",
    uso1: "Gaming: Dedicado",
    uso2: "Arquitectura, Diseño, Edición: Avanzado",
    uso3: "Hogar, Oficina: Avanzado",
    pantalla: "Tamaño 15.6''" + " y su resolución es de 1920x1080",
    price: 322089,
  },
  {
    id: 2,
    image: "https://www.venex.com.ar/products_images/1654711035_4.png",
    title: "APPLE MACBOOK PRO M1 PRO",
    descripcion:
      "M1 Pro escala la increíble arquitectura M1 a nuevas alturas, y por primera vez, traen una arquitectura de sistema en un chip (SoC) a una computadora portátil profesional.",
    almacenamiento: "1 TB",
    gpu: "Por defecto",
    ram: "16 GB",
    cpu: "Apple: M1 Pro",
    sistema: "IOS",
    uso1: "Gaming: Dedicado",
    uso2: "Arquitectura, Diseño, Edición: Avanzado",
    uso3: "Hogar, Oficina: Avanzado",
    pantalla: "Tamaño 16'' y su resolución es de 3456 x 2234",
    category: "APPLE",
    price: 988249,
  },
  {
    id: 3,
    image:
      "https://www.venex.com.ar/products_images/1656433721_sin_t_tulo-1.png",
    title: "GIGABYTE G5 15 I5 11400H RTX3050",
    descripcion:
      "M1 Pro escala la increíble arquitectura M1 a nuevas alturas, y por primera vez, traen una arquitectura de sistema en un chip (SoC) a una computadora portátil profesional.",
    almacenamiento: "1 TB",
    gpu: "Por defecto",
    ram: "16 GB",
    cpu: "Apple: M1 Pro",
    sistema: "IOS",
    uso1: "Gaming: Dedicado",
    uso2: "Arquitectura, Diseño, Edición: Avanzado",
    uso3: "Hogar, Oficina: Avanzado",
    pantalla: "Tamaño 16'' y su resolución es de 3456 x 2234",
    category: "GIGABYTE",
    price: 281990,
  },
  {
    id: 4,
    image:
      "https://www.venex.com.ar/products_images/1626471024_notebook-lenovo-ideapad-s145-15iil-i3-1005-g1-4gb-1tb-15.6-free.jpg",
    title: "LENOVO IDEAPAD S145 15IIL",
    descripcion:
      "M1 Pro escala la increíble arquitectura M1 a nuevas alturas, y por primera vez, traen una arquitectura de sistema en un chip (SoC) a una computadora portátil profesional.",
    almacenamiento: "1 TB",
    gpu: "Por defecto",
    ram: "16 GB",
    cpu: "Apple: M1 Pro",
    sistema: "IOS",
    uso1: "Gaming: Dedicado",
    uso2: "Arquitectura, Diseño, Edición: Avanzado",
    uso3: "Hogar, Oficina: Avanzado",
    pantalla: "Tamaño 16'' y su resolución es de 3456 x 2234",
    category: "LENOVO",
    price: 124429,
  },
  {
    id: 5,
    image:
      "https://www.venex.com.ar/products_images/1645726383_notebook-lenovo-thinkbook-g2-core-i5-1135g7-8gb-ssd-256gb-15.6-free.jpg",
    title: "LENOVO THINKBOOK G2 CORE I5 1135G7",
    descripcion:
      "M1 Pro escala la increíble arquitectura M1 a nuevas alturas, y por primera vez, traen una arquitectura de sistema en un chip (SoC) a una computadora portátil profesional.",
    almacenamiento: "1 TB",
    gpu: "Por defecto",
    ram: "16 GB",
    cpu: "Apple: M1 Pro",
    sistema: "IOS",
    uso1: "Gaming: Dedicado",
    uso2: "Arquitectura, Diseño, Edición: Avanzado",
    uso3: "Hogar, Oficina: Avanzado",
    pantalla: "Tamaño 16'' y su resolución es de 3456 x 2234",
    category: "LENOVO",
    price: 194709,
  },
  {
    id: 6,
    image:
      "https://www.venex.com.ar/products_images/1652467502_notebook-asus-zenbook-ux425ea-ki837w-i5-1135g7-8gb-ssd-512gb-14-w11.jpg",
    title: "ASUS ZENBOOK UX425EA-KI837W I5",
    descripcion:
      "M1 Pro escala la increíble arquitectura M1 a nuevas alturas, y por primera vez, traen una arquitectura de sistema en un chip (SoC) a una computadora portátil profesional.",
    almacenamiento: "1 TB",
    gpu: "Por defecto",
    ram: "16 GB",
    cpu: "Apple: M1 Pro",
    sistema: "IOS",
    uso1: "Gaming: Dedicado",
    uso2: "Arquitectura, Diseño, Edición: Avanzado",
    uso3: "Hogar, Oficina: Avanzado",
    pantalla: "Tamaño 16'' y su resolución es de 3456 x 2234",
    category: "ASUS",
    price: 263529,
  },
  {
    id: 7,
    image:
      "https://www.venex.com.ar/products_images/1637336314_notebook-asus-rog-zephyrus-ga401ihr-ryzen-7-4800hs-16gb-512gb-1650-14-w10.jpg",
    title: "ASUS ROG ZEPHYRUS GA401IHR RYZEN 7",
    descripcion:
      "M1 Pro escala la increíble arquitectura M1 a nuevas alturas, y por primera vez, traen una arquitectura de sistema en un chip (SoC) a una computadora portátil profesional.",
    almacenamiento: "1 TB",
    gpu: "Por defecto",
    ram: "16 GB",
    cpu: "Apple: M1 Pro",
    sistema: "IOS",
    uso1: "Gaming: Dedicado",
    uso2: "Arquitectura, Diseño, Edición: Avanzado",
    uso3: "Hogar, Oficina: Avanzado",
    pantalla: "Tamaño 16'' y su resolución es de 3456 x 2234",
    category: "ASUS",
    price: 409939,
  },
  {
    id: 8,
    image:
      "https://www.venex.com.ar/products_images/1652468601_notebook-asus-rog-ryzen-7-6800h-16gb-ssd-512gb-rtx-3060-15.6-w11.jpg",
    title: "ASUS ROG G513RM RYZEN 7 6800H 16GB",
    descripcion:
      "M1 Pro escala la increíble arquitectura M1 a nuevas alturas, y por primera vez, traen una arquitectura de sistema en un chip (SoC) a una computadora portátil profesional.",
    almacenamiento: "1 TB",
    gpu: "Por defecto",
    ram: "16 GB",
    cpu: "Apple: M1 Pro",
    sistema: "IOS",
    uso1: "Gaming: Dedicado",
    uso2: "Arquitectura, Diseño, Edición: Avanzado",
    uso3: "Hogar, Oficina: Avanzado",
    pantalla: "Tamaño 16'' y su resolución es de 3456 x 2234",
    category: "ASUS",
    price: 549019,
  },
  {
    id: 9,
    image: "https://www.venex.com.ar/products_images/1655987042_cucarda.jpg",
    title: "ACER ASPIRE 5 I7 10510U 8GB SSD 256GB",
    descripcion:
      "M1 Pro escala la increíble arquitectura M1 a nuevas alturas, y por primera vez, traen una arquitectura de sistema en un chip (SoC) a una computadora portátil profesional.",
    almacenamiento: "1 TB",
    gpu: "Por defecto",
    ram: "16 GB",
    cpu: "Apple: M1 Pro",
    sistema: "IOS",
    uso1: "Gaming: Dedicado",
    uso2: "Arquitectura, Diseño, Edición: Avanzado",
    uso3: "Hogar, Oficina: Avanzado",
    pantalla: "Tamaño 16'' y su resolución es de 3456 x 2234",
    category: "ACER",
    price: 197639,
  },
  {
    id: 10,
    image: "https://www.venex.com.ar/products_images/1653580395_fse.png",
    title: "APPLE MACBOOK PRO M1 PRO 16GB",
    descripcion:
      "M1 Pro escala la increíble arquitectura M1 a nuevas alturas, y por primera vez, traen una arquitectura de sistema en un chip (SoC) a una computadora portátil profesional.",
    almacenamiento: "1 TB",
    gpu: "Por defecto",
    ram: "16 GB",
    cpu: "Apple: M1 Pro",
    sistema: "IOS",
    uso1: "Gaming: Dedicado",
    uso2: "Arquitectura, Diseño, Edición: Avanzado",
    uso3: "Hogar, Oficina: Avanzado",
    pantalla: "Tamaño 16'' y su resolución es de 3456 x 2234",
    category: "APPLE",
    price: 878459,
  },
  {
    id: 11,
    image:
      "https://www.venex.com.ar/products_images/1656435818_sin_t_tulo-1.png",
    title: "GIGABYTE AERO XE5 I7 12700H 16GB",
    descripcion:
      "M1 Pro escala la increíble arquitectura M1 a nuevas alturas, y por primera vez, traen una arquitectura de sistema en un chip (SoC) a una computadora portátil profesional.",
    almacenamiento: "1 TB",
    gpu: "Por defecto",
    ram: "16 GB",
    cpu: "Apple: M1 Pro",
    sistema: "IOS",
    uso1: "Gaming: Dedicado",
    uso2: "Arquitectura, Diseño, Edición: Avanzado",
    uso3: "Hogar, Oficina: Avanzado",
    pantalla: "Tamaño 16'' y su resolución es de 3456 x 2234",
    category: "GIGABYTE",
    price: 708990,
  },
  {
    id: 12,
    image:
      "https://www.venex.com.ar/products_images/1656434718_sin_t_tulo-1.png",
    title: "GIGABYTE AORUS 17G I7 11700H 32GB",
    descripcion:
      "M1 Pro escala la increíble arquitectura M1 a nuevas alturas, y por primera vez, traen una arquitectura de sistema en un chip (SoC) a una computadora portátil profesional.",
    almacenamiento: "1 TB",
    gpu: "Por defecto",
    ram: "16 GB",
    cpu: "Apple: M1 Pro",
    sistema: "IOS",
    uso1: "Gaming: Dedicado",
    uso2: "Arquitectura, Diseño, Edición: Avanzado",
    uso3: "Hogar, Oficina: Avanzado",
    pantalla: "Tamaño 16'' y su resolución es de 3456 x 2234",
    category: "GIGABYTE",
    price: 657990,
  },
];
